### ISSUE TITLE
EntityMarking seems unimplemented

### ISSUE THREAD

**Issue by joeclarkia** [open-dis/open-dis-javascript#13]
The dis7 EntityMarking.js files implements the marking character string as a single byte, instead of the specified 12 bytes (11 + NULL terminator).  I have sample code that I believe will implement this correctly -- I will aim to commit this code to a forked repo (or I could put a patch here) for consideration.

**Comment by leif81** [comment]
Thank-you @joeclarkia . Yes if you believe it's a bug we always welcome and encourage pull requests to fix them!

**Comment by joeclarkia** [comment]
https://github.com/open-dis/open-dis-javascript/pull/14
