### ISSUE TITLE
Variable Datum and Chunk are Broken

### ISSUE THREAD

**Issue by crhowell3** [open-dis/open-dis-javascript#19]
Creating an urgent pull request to address an issue that affects all PDUs that leverage the Chunk and the VariableDatum files. Will have it ready shortly, and I would recommend a quick release to be pushed out to NPM to correct this bug.

**Comment by leif81** [comment]
Thank-you for this @crhowell3 

A new version v1.3.5 has been released to NPM just now.

https://www.npmjs.com/package/open-dis/v/1.3.5
