### ISSUE TITLE
EntityMarking: characters array length is wrong

### ISSUE THREAD

**Issue by joeclarkia** [open-dis/open-dis-javascript#21]
https://github.com/open-dis/open-dis-javascript/blob/master/src/dis7/EntityMarking.js#L26

The character array length is set to 12, but according to the standard, it should be 11.  This is an easy mistake because the total EntityMarking length is 12, but the first byte is a character set byte.

Sidenote: I was interested to submit this, my second issue/codefix for open-dis-javascript.  I was a little less excited when I realized that *I* was the one who introduced this bug -- oops!

**Comment by leif81** [comment]
Thanks for the report @joeclarkia 

Will you be interested in submitting a pull request?

**Comment by joeclarkia** [comment]
https://github.com/open-dis/open-dis-javascript/pull/23

I think that's all that is required to fix this.
