### ISSUE TITLE
Push New Version to npm?

### ISSUE THREAD

**Issue by nickclark2016** [open-dis/open-dis-javascript#9]
Question/issue is the title.  Would it be possible to get 1.3.1 onto npm since it has bug fixes for encode?

**Comment by leif81** [comment]
Yes good idea, I will try to get to this today.

**Comment by leif81** [comment]
1.3.1 has been published.

https://www.npmjs.com/package/open-dis

@nickclark2016 let me know if you have any issues.

**Comment by nickclark2016** [comment]
I'll check in the morning. Much appreciated!

**Comment by nickclark2016** [comment]
@leif81 So looking at what's on npm, it appears that it's the source version and not the version that is compiled down to a `dis.js` file.  Is that possible to resolve so I don't need to include each file manually?

**Comment by leif81** [comment]
Oops my intent was to publish the minified version. Will look into.

**Comment by leif81** [comment]
@nickclark2016 ok give 1.3.3 a try. It will include a dist folder with dis6.min.js and dis7.min.js. Choose one.

Hopefully this works this time but let me know again if you have issues.

**Comment by leif81** [comment]
Edit: Sorry I mean try 1.3.2

**Comment by nickclark2016** [comment]
No worries! It looks like doing this:

```ts
import { ... } from 'open-dis';
```

Doesn't work anymore.  Instead, I have to do:

```ts
import { ... } from 'open-dis/dist/dis6.min';
```

Is this expected?
